carpentries-lab/deep-learning-intro

_episodes/02-pytorch.md

print("Epoch {} - loss: {}".format(epoch, cost.item()))
instead of
print("Epoch {} - loss: {}".format(epoch, loss.item()))
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson …

Corrected code

---

CONTRIBUTING.md

I placed the remark at the end of the contributing.md in hope that once we pull from the official contributing.md, `git` might be able to merge that more easily. This assumption has not been tested on my side.

start a section to list conventions used for the material

---

_episodes/04-networks-are-like-onions.md

The CI pipeline is stopped at one position recently, where an output block was marked as `language-python` type codeblock.

fix wrong codeblock label

---

.github/workflows/inline-code.yml

Sometimes we want to trigger a code check without pushes / PRs, namely when the code checker is updated.

Add event to trigger code check

---

_episodes/02-keras.md

Nothing is now stored as target until it has been onehot encoded. The constant overwriting was confusing.
Fixes issue #103

Remove redundant use and assignment of target in episode 2

---

_episodes/02-keras.md

All text and code relating to setting the optimizer are now moved into stage 5 of the process (choose a loss function and optimizer) instead of stage 6 (train the model).
fixes #85

Moving setting the optimizer to stage 5

---

_episodes/02-keras.md

Among other minor edits, the spelling for one-hot encoding (https://en.wikipedia.org/wiki/One-hot) is now consistent across the document.

02-keras.md: fix spelling

---

_episodes/03-monitor-the-model.md

This changes 
model.compile(#...
loss='mse',
#...)
to just
model.compile( loss='mse')
(and the same for the following example with the optimizer)
to make it pass the code check by using syntactically valid python. Is this acceptable or does it make it harder for a learner to understand?
We could also avoid this issue by not marking it as a python block of code or simply not presenting the full statement until we've covered both the loss and optimizer.

fixing code to pass checker

---

setup.md

The packages conda and pip work regardless of the operating system once their installers have been run successfully.
In the previous version, the commands to run conda/pip were framed as Bash commands.
This implied that the users had to use a Unix Shell proper or a simulator of it, which is not needed; in turn this might lead to the impression that troubleshooting installation issues is harder than it actually is.
Therefore, the instructions to install packages have been framed as generic source code. 
Some context information clarifies the relationship between Anaconda, Python, Conda, pip and the operating system.
Other minor spelling glitches have been fixed.
@dsmits

setup.md: clarify usage of conda pip and OSs

---

_episodes/02-keras.md

> Episode 2 "This is a commonly used activation functions" should be singular`
> functions changed to function

Fix typos #213 Episode 2

---

_extras/design.md

> "networt" instead of "network" twice near the end of the Lesson Design page **_- Changed both 'networt' to 'network'_**

Fix typos #213 Lesson Design Page

---

_episodes/03-monitor-the-model.md

> Episode 3 explore the dataset exercise "variabel types" _**- changed to 'variable'**_
> Episode 3 "Split data into training, validation, and test set" exercise has an extra "`" to format code _**- removed grave symbol**_
> Episode 3 "to splot if" _**- changed to 'split'**_
> Episode 3 "stop training of the" _**- changed to 'if'**_

Fix typos #213 Episode 3

---

_episodes/04-networks-are-like-onions.md

> Episode 4 solution "one signal data point" _**- Changed to 'single'**_
> Episode 4 solution "add a an extra" _**- Removed 'a'**_

Fix typos #213 Episode 4

---

_episodes/01-introduction.md

Add info on pytorch lightning to adress #212.
I'm not sure about adding JAX, I am not so familiar with it myself and I think it's not a very suitable library for beginners in deep learning.

Add info on pytorch lightning #212

---

_episodes/04-advanced-layer-types.md

I added a brief note to the Advanced Layers episode that explains the choice to use the SparseCategoricalCrossentropy() function.

Explained use of SparseCategoricalCrossentropy fxn

---

_episodes/03-monitor-the-model.md
_episodes/04-advanced-layer-types.md

One of the exercises in chapter 4 is currently incorrectly formatted.
There are also a few callouts/exercises/solutions that had whitespace at the start that caused indentation problems if copy-pasting to a cell.

Cleanup whitespace and fix syntax of exercise in chapter 4

---

setup.md

fixes #89 
Modified setup to install packages in a conda environment instead of in base. 
Tf is installed using pip as per the official recommendation. Jupyter is installed explicitly with conda.

added conda environment in setup

---

_episodes/01-introduction.md
setup.md

Fixes #320 
At the time, the latest package versions are:
sklearn version:  1.2.2
seaborn version:  0.12.2
pandas version:  1.5.3
Keras version:  2.12.0
Tensorflow version:  2.12.0

installed packages versions updated

---

_episodes/04-advanced-layer-types.md

This PR links out to a more detailed description of how convolution (in the form of a Gaussian blur) can be applied at the boundaries of an image. Related to discussion in #287

link out to DC Image curriculum

---

setup.md

I added some text to the setup instructions clarifying that Windows users should open an Anaconda prompt to create the conda environment

Clarify use of terminal (Mac) vs Anaconda prompt (Windows)

---

README.md
setup.md

This makes the Binder Hub links more prominent by adding them to the readme and setup instructions. This can be used as a fallback environment for anybody who can't install anaconda on their own computer.

324 binder links

---

episodes/2-keras.Rmd
episodes/3-monitor-the-model.Rmd
episodes/4-advanced-layer-types.Rmd

Greatly reduces the time spent on data exploration and processing, so that there is more time for deep learning!
In general I moved stuff out of exercises, and added a simple MC question instead to activate everyone. This should greatly improve the speed!
In episode 4 I also removed plotting the images, we want people to learn deep learning and not how to plot images (even though it is a lot of fun of course)
Fixes #258

Shorten data exploration in episode 2, 3 and 4

---

episodes/2-keras.Rmd

This PR fixes a bug in step 4 of episode 2. Here two seeds are set to ensure consistent results. However the second seed is not correct or depricated
`from tensorflow.random import set_seed
set_seed(2)`
instead the `keras.utils.set_random_seed` should be used to ensure consistent results. The first seed from numpy is also still neccesary.
fixes #388

Bug fix: random seed for keras

---

episodes/1-introduction.Rmd
episodes/2-keras.Rmd
episodes/3-monitor-the-model.Rmd
episodes/4-advanced-layer-types.Rmd
episodes/fig/graphviz/pipeline.dot

Rename hyperparameter tuning to refine the model

---

learners/setup.md

This resolves the final point of #431 regarding terminal terminology and keeping it clear for all users (Windows/Mac/Linux)

fixed terminal terminology for all users

---

episodes/5-outlook.Rmd
learners/reference.md

Fixes #424 
@reviewer: 
* Is this the right place to put this?
* Do you find this a useful addition?
* I did not put this in the learning objectives and questions, it is more a: 'did you know?' section? Do you agree?
NB: the referred article is not open-source (unfortunately the forefront of research related to ChatGPT isn't), so I could not use images from the paper. But I think my highly simplified examples are good enough to understand the approach (maybe even simpler than the images in the paper).

Add a discussion on LLMs and prompt engineering

---

episodes/1-introduction.Rmd
episodes/4-advanced-layer-types.Rmd
learners/setup.md

The api of keras has stayed the same thankfully. Only the version check of keras didn't exist anymore, but a version check of tensorflow show be sufficient.
I also fixed some small bugs that I encountered.

436 update libraries and check if code examples still work

---

episodes/1-introduction.Rmd
episodes/2-keras.Rmd
episodes/3-monitor-the-model.Rmd
episodes/4-advanced-layer-types.Rmd
episodes/5-outlook.Rmd

Fixes:
* [Do not use " in objectives and questions](https://github.com/carpentries-incubator/deep-learning-intro/commit/bf137142a2211ced0a1e687414bb03e1337cc399)
* [Do not use " in keypoints](https://github.com/carpentries-incubator/deep-learning-intro/commit/1ea9ab6a8b4e691fb5c1b1f0f04c3734b060b7b8)
* [Fix alt text huber loss image](https://github.com/carpentries-incubator/deep-learning-intro/commit/8d9c044229e2c32137d4685e7c31105cf8f6dec1)

Small fixes from Carpentries Lab review

---

config.yaml
episodes/1-introduction.Rmd
episodes/2-keras.Rmd
episodes/3-monitor-the-model.Rmd
episodes/4-advanced-layer-types.Rmd
index.md
instructors/schedule.md

- Add an example schedule
- Add reminders for instructor switches/breaks in episodes.
Fixes #446

Deal with long episodes

---

config.yaml

`schedule.md` should not be in the `instructors` section, this fixes #458 .

Remove schedule.md from config.yaml.

---

episodes/1-introduction.Rmd

I didn't like the figure captions (activation function labels) showing up below each horizontal line -- was confusing to read. Added captions above each figure.

improve figure captions for activation functions

---

episodes/1-introduction.Rmd

Fix captions position activation function exercise

---

episodes/2-keras.Rmd

Researchers at my university (University of Wisconsin-Madison) rely heavily on both Hugging Face and MONAI for pretrained models.

Add Hugging Face and MONAI as hubs for pretrained models

---

learners/setup.md

I ran into an odd bug while prepping to teach this workshop last week. With the current workshop environment running on Windows 10, I ran into this issue: https://stackoverflow.com/questions/77165100/only-the-first-row-of-annotations-displayed-on-seaborn-heatmap
Updating both matplotlib and seaborn seemed to resolve the issue: 
`pip install seaborn --upgrade`
`pip install matplotlib --upgrade`
I propose we add these pip statements to the setup instructions.

Fix heatmap plotting bug

---

episodes/1-introduction.Rmd

Properly introduce activation functions

---

README.md

Closes #493 
Also adds a missing 'Carsten' (#468).

Refine rendering locally instructions

---

episodes/1-introduction.Rmd

There seem to be two issues here:
- The string ``{{ page.root }}` is not resolved, but becomes part of the literal URL in the rendered HTML
- The anchor is called `software-setup`, not `setup`
Fixes #502 
The proposed fix is to remove the `{{ page.root }}` entirely. This works locally, but I am not entirely certain about potential side effects.

Fix links to software setup.

---

episodes/1-introduction.Rmd

Fix link to setup instructions

---

README.md
index.md

Remove call for beta testers.

---

episodes/1-introduction.Rmd

Improve explanation of images in episode 1

---

learners/setup.md

Fixes #507 (the technical part).

Convert Troubleshooting into normal header instead of a discussion div.

---

episodes/2-keras.Rmd

Explain random seeds in episode 2

---

episodes/1-introduction.Rmd

- Add an instructor note for MathJax issues on Chrome/MacOs: https://physics.meta.stackexchange.com/questions/14408/bug-in-mathjax-rendering-using-chrome
See https://github.com/carpentries-lab/reviews/issues/25#issuecomment-2593711592

Add instructor box for fixing MathJax issues on Chrome/MacOS.

---

learners/setup.md

Replace the instructions for installing `tensorflow-metal` with a comment because it is currently broken (see link in added comment).

Replace tensorflow-metal installation instructions

---

index.md

I noticed while browsing the [_Summary and Schedule_ / index page in the instructor view](https://carpentries-lab.github.io/deep-learning-intro/instructor/index.html) that the link to the repository README in the 'We can help you out with teaching this lesson' expandable points to the repository in the `carpentries-incubator` organization rather than the current `carpentries-lab` and so is broken. This PR just updates the URL to go to the correct README file.
Thanks to everyone who has contributed to such a great set of lesson material 😄!

Update link to repository README

---

episodes/3-monitor-the-model.md

Partially addresses #429 by expanding alt text descriptions for images in episode 3. I also moved one part of a paragraph below the relevant figure since I think the lesson content makes more sense that way around.

Expand alt text descriptions
