- _episodes/01-introduction.md
> Fixed typo

- _episodes/01-introduction.md
to display y axis labels
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please …
> Changed code for activation functions

- _episodes/01-introduction.md
> Corrected typos

- _episodes/01-introduction.md
in the solution to plot the modified unit step function
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a …
> Defined x before y

- _episodes/01-introduction.md
> Corrected indentation in the perceptron code

- _episodes/01-introduction.md
> Link to iris on en.wiki

- _episodes/01-introduction.md
> Changed code for reading iris data

- _episodes/01-introduction.md
for
apply our neural network to our dataset
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …
> {: .language-python}

- _episodes/01-introduction.md
single layer back propagation
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please …
> Changed code for

- _episodes/02-pytorch.md
in out.backward()
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate …
> Corrected typo

- _episodes/02-pytorch.md
> Changed description for torch.nn.MSELoss()

- _episodes/02-pytorch.md
added
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time …
> Corrected code for ### Testing the network

- _episodes/03-regression.md
> Defined D_out from the begining

- _episodes/03-regression.md
Figure (Model_validation.png) to be included
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …
> Added a graph in the # Test/validation

- _episodes/03-regression.md
> Inserted Model_validation.png

- _episodes/04-ann.md
> move train and test in class

- _episodes/04-ann.md
> added challenge

- _episodes/02-pytorch.md
> Deleted 2nd perceptron call

- setup.md
PyTorch is not available for 32-bit CPU.
Hi, I suggest a comment in the setup. 
Would there be a solution for people who do not have a 64-bit machine??? Run on sigma2 or something similar?
> 64-bit needed

- _episodes/04-ann.md
and call self.forward() to make it easier to explain.
> bug-fix: not network (object) but call functions

- README.md
> fix link to lesson in README file

- _extras/design.md
- _includes/base_path.html
- _includes/links.md
Design motivation and ideas from #49
> summarizing the design considerations for this material

- _episodes/02-keras.md
The first line refers to it as penguin_filtered and subsequent lines are penguins_filtered
> adding missing s to the creation of penguin_filtered

- _episodes/01-introduction.md
I've roughly halved the amount of text in the deep learning workflow description but still kept it for now. Let's see how well it works during the trial lesson next week to decide if it should stay at all.
> Reducing the amount of text/detail in the deep learning workflow

- _episodes/02-keras.md
as reported by learners during test teaching
> make text consistent with output

- _episodes/02-keras.md
see also https://www.tensorflow.org/api_docs/python/tf/random/set_seed
> set random seed compliant with tf2+

- setup.md
> penguins dataset linked to contained more than necessary

- _episodes/02-keras.md
suggest by learner during trial lesson 20210622
> refine exercise to distinguish first and second half

- _episodes/01-introduction.md
and exclude computational prohibitive answers (suggested by a learner)
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your …
> more fine grained language to justify solution

- _episodes/02-keras.md
use `sum` instead of `value_counts` to obtain number of samples per class, solving issue #95 .
> Changed solution to exercise, #95

- .github/workflows/inline-code.yml
I made a small tool that extracts all the code examples from an episode and runs them as one big python file.
I made an initial github action that uses this tool. If the code runs without errors it should succeed, the tool does not check whether the output is correct.
> Code check action

- _episodes/03-monitor-the-model.md
There was a formatting bug so that the solution did not show.
> Fixed formatting of exercise

- _episodes/03-monitor-the-model.md
Add questions and update objectives.
> add questions and remove former objective

- _episodes/01-introduction.md
- _episodes/02-keras.md
Here is a proposal to update the deep learning workflow that makes episode 2 flow more nicely.
Please let me know if you agree with this proposal.
> Small optimization to workflow that flows better for episode 2 at least

- _extras/guide.md
- setup.md
I updated the setup instructions and instructor notes.
Fixes #100 #91 #90.
> Update setup instructions

- _episodes/03-monitor-the-model.md
- Make the code blocks more consistent (e.g. variable naming)
- Add further hints to the excercises
- Add further explanations
- Move the baseline creation from the end to the point after the first model evaluation to address #132
> Update episode 3 after first tests

- _episodes/03-monitor-the-model.md
Fixes #123 
Add output box and explanation of parameters of batchnorm to episode 3.
> Add explanation batchnorm #123

- _episodes/02-keras.md
> Rephrase question to fix #137

- setup.md
Using tensorflow version 2.5.0 fixes #136
> Update tensorflow version to fix #136

- _episodes/02-keras.md
- _episodes/03-monitor-the-model.md
- _episodes/04-networks-are-like-onions.md
Fixed some typos, so I'd say this PR is very low priority ;) - I also didn't crosscheck if one of the open PRs already addresses some of them.
Also made sure to capitalize Keras everywhere except in code..
> fixed some typos

- setup.md
Closes #167 
I got this solution from a colleague who uses windows. Haven't been able to try it out myself.
> Added special installation instructions for windows

- .github/workflows/inline-code.yml
Searched for any mention of the BBQ dataset and removed it.
Not related to an existing issue.
> Removed bbq dataset from CI

- _episodes/03-monitor-the-model.md
Closes #160 
Closes #105 
Pointed all links to smaller dataset.
Changed outputs and exercise answers where the larger dataset was used.
> Use light dataset

- _episodes/03-monitor-the-model.md
This PR goes over episode 3 again and extracts advances in content that are stuck in exercises.
Closes #165
> extract content from episode 3 exercises

- _config.yml
- index.md
Updates the _config.yml to beta stage and adds a banner to the home page welcoming feedback via github issues or slack.
> Move the lesson to beta stage

- _episodes/04-networks-are-like-onions.md
multiply n_input_items by 3 since images are RGB
> update no. of parameters calculation

- _episodes/01-introduction.md
- _episodes/02-keras.md
- _episodes/03-monitor-the-model.md
- _episodes/04-networks-are-like-onions.md
- setup.md
this is work done in preparation for a workshop held by ENCCS on Feb 22-23
> fix typos and formatting and add an exercise

- _episodes/02-keras.md
The variables names are lower-case. 
All penguin-related variable are named `penguins_*`. 
An output line has been changed since I obtained a slightly different output.
> 02-keras.md:; simplify code lines

- _episodes/04-advanced-layer-types.md
Changing the name of episode 4, to address issue #218.
> Change name of episode 4 #218

- .gitignore
- _episodes/03-monitor-the-model.md
> Issue 211 validation set

- AUTHORS
- README.md
> Updated contributors

- _episodes/04-advanced-layer-types.md
The creator of the CIFAR-10 dataset wants you to cit his tech report. He says so at the bottom of the site we refer to: https://www.cs.toronto.edu/~kriz/cifar.html
This is a small PR where I add this reference.
> The creator of the cifar-10 dataset wants to be cited

- _episodes/01-introduction.md
- _episodes/03-monitor-the-model.md
> Replaced "validation set" with "test set" in step 8

- _episodes/03-monitor-the-model.md
just a minor fix on capitalization
> capitalization fix

- setup.md
Fixes #246 
Please note: there are currently no links specific for operating systems, the OS is automatically detected.
> Update anaconda distribution links

- reference.md
Add list of external references to the References page. Fixes #185 and #116.
> Add external references, #185 and #116

- _episodes/03-monitor-the-model.md
This PR address issues #117 and #249.
The episode has been rearranged marginally to fit in to the 10-step procedure outlined in prior episodes.
> Episode3 add workflow steps#117

- setup.md
Fixes #138. 
@CunliangGeng I know on your machine you had no problems installing tensorflow (probably with the most recent Anaconda or Miniconda). I still have problems installing with miniforge. This is a workaround that could work for people getting into that problem.
> Add troubleshooting for M1 Macs

- _episodes/01-introduction.md
To solve issue #250 .
Note: the equation is not rendered properly.  I check the [carpentries example lesson](https://carpentries.github.io/lesson-example/04-formatting/index.html#adding-formatted-equations), the equations are not rendered properly neither. Will create [a issue](https://github.com/carpentries/lesson-example/issues/345) for that.
> add exercise

- CONTRIBUTING.md
> Add rules on resolving merge conflicts to PR

- _episodes/03-monitor-the-model.md
> fix wrong solution

- setup.md
Fixes #245 
Changed all reference to notebooks in set-up to jupyterlab.
> modified set-up to include jupyterlab

- _episodes/01-introduction.md
- _episodes/02-keras.md
- _episodes/03-monitor-the-model.md
- _episodes/04-advanced-layer-types.md
> Slightly rephrase objectives and questions

- _episodes/01-introduction.md
- _episodes/03-monitor-the-model.md
- _episodes/04-advanced-layer-types.md
Addressed the issues that popped up in #288
> 288 make sure the content matches the objectives for each episode

- _episodes/04-advanced-layer-types.md
> Add workaround for ssl error loading cifar-10 dataset

- _episodes/01-introduction.md
- _episodes/02-keras.md
- _episodes/03-monitor-the-model.md
- _episodes/04-advanced-layer-types.md
Fixes #271 
Modified all alt-text for images making it more explicit and well-defined.
Removed contractions leaving only a few as meaningful.
> 271 accessibility

- _episodes/02-keras.md
> Add exercise on one-hot encoding

- reference.md
I added glosario links wherever they were available.
To keep things consistent I will try to get the missing definitions into glosario as well.
> Added links to glosario wherever I could

- _episodes/04-advanced-layer-types.md
> Add exercise on why convnets

- _episodes/03-monitor-the-model.md
> fix block formatting

- _episodes/02-keras.md
> Update timing episode 2

- episodes/3-monitor-the-model.Rmd
Moves 'Set expectations: How difficult is the defined problem?' to the section before (evaluate the model)
> Move baseline to logical section

- episodes/4-advanced-layer-types.Rmd
Adds headers for the workflow steps in episode 4
> Add workflow steps episode 4

- episodes/1-introduction.Rmd
> added neuron output equation

- episodes/2-keras.Rmd
> Fix timing of episode 2

- episodes/1-introduction.Rmd
- episodes/2-keras.Rmd
Fixes #296 and explains trainable and non-trainable parameters in a callout
> Parameter types explaination

- episodes/3-monitor-the-model.Rmd
> Improve answer to reduce number of nodes exercise

- episodes/3-monitor-the-model.Rmd
- episodes/4-advanced-layer-types.Rmd
> Make plot_history() function in episode 3 and 4 functional

- config.yaml
- episodes/5-outlook.Rmd
> Add outlook episode

- config.yaml
> Mark lesson as stable

- episodes/4-advanced-layer-types.Rmd
> Correct phrasing around dropout rate

- episodes/1-introduction.Rmd
- episodes/fig/01_identity_function.svg
- episodes/fig/01_relu.svg
- episodes/fig/01_sigmoid.svg
> Activation functions exercise

- CITATION
- CITATION.cff
- README.md
Fixes #222 
Removed AUTHORS since it is redundant.
Created with https://citation-file-format.github.io/cff-initializer-javascript/
> Fill CITATION.cff file

- episodes/4-advanced-layer-types.Rmd
> Explain why we do not one-hot encode in episode 4

- instructors/instructor-notes.md
> Add deep learning workflow to instructor notes.

- episodes/2-keras.Rmd
> Add instructor notes on episode 2 being quite basic

- learners/reference.md
> Link all terms in reference to glosario

- episodes/4-advanced-layer-types.Rmd
Fixes #404 . It actually also adds a callout box, since for self-learning it is also good to know this.
> Introduce googling for existing implementations

- episodes/4-advanced-layer-types.Rmd
> Renames test data to val data in episode 4

- episodes/5-outlook.Rmd
> Add part on organising deep learning projects.

- episodes/3-monitor-the-model.Rmd
> Add instructor note on copy-pasting code in episode 3

- episodes/2-keras.Rmd
Fixes #395 . I choose `features`, because it matches well with `target` that we already had. I think it is clear enough that we are dealing with penguins.
> Rename penguins_features to features episode 2

- episodes/5-outlook.Rmd
Fixes #383 . In fact, it adds some questions to actually test if students understand the siamese network architecture.
> Update question on understanding siamese network

- index.md
Fixes #430 and #439:
'the check boxes in the prereqs render poorly in the workbench + are an accessibility flag bc they're unlabeled "form elements" these should be removed'
> Improve styling welcome and prerequisites

- episodes/1-introduction.Rmd
Addresses one item in the list from #429
> Expand alt-text for Huber loss figure

- episodes/4-advanced-layer-types.Rmd
As suggested at today's sprint, adding a conclusion and an Instructor Note about the example data in episode 4
> Add conclusion to Episode 4

- episodes/2-keras.Rmd
> [Episode 2] Make shape a tuple

- episodes/1-introduction.Rmd
- episodes/2-keras.Rmd
- episodes/3-monitor-the-model.Rmd
- episodes/4-advanced-layer-types.Rmd
> Fix casing of deep learning, machine learning, neural networks, see issue #241

- episodes/2-keras.Rmd
Shape should be surrounded by parentheses with a comma separating the two dimensions specified
> Fix call to keras.Input(shape=(X_train.shape[1], ))

- learners/reference.md
Simon's recently published book is free and comes with colab notebooks to work through each chapter. I think this book is the right level of difficulty for many people who take the Intro DL workshop. It also has some important chapters on more modern concepts, including the double descent phenomenon.
> Add one additional book to the list

- episodes/2-keras.Rmd
Very minor, but I like to show the class the resulting df before we plot it
> Add a call to .head() after prepping confusion_df

- README.md
- episodes/1-introduction.Rmd
- index.md
- instructors/instructor-notes.md
> Refer to lesson content with lesson

- episodes/2-keras.Rmd
> Emphasise goal in episode 2

- episodes/6-outlook.Rmd
Fixes from #515 for Outlook section.
> Issue_515/outlook

- index.md
> Link to ML and other deep learning lesson in introduction

- paper.bib
- paper.md
> Cite other carpentries DL lesson in paper

- AUTHORS
- CITATION.cff
Adds Yonglei and me to the AUTHORS file
> Add contributing authors from ENCCS

- episodes/2-keras.Rmd
Add a link to the Transfer Learning episode, remove Transfer Learning from section title in episode 2.
> Add link to episode 5.

- config.yaml
@svenvanderburg is there a more appropriate contact email address we can use than The Carpentries' address, please?
> Configure for The Carpentries Lab

- renv/activate.R
- renv/profile
- renv/profiles/lesson-requirements/renv.lock
- renv/profiles/lesson-requirements/renv/.gitignore
- renv/profiles/lesson-requirements/renv/settings.json
This will probably fix #552. But please see #558, since we might be able to avoid this altogether.
> add renv directory

- episodes/4-advanced-layer-types.md
Updated Episode 4 to be consistent with Episode 3
> create_nn() now takes the input shape as an argument

- episodes/5-transfer-learning.md
self-explanatory -- minor formatting fix for bulleted list. A newline was missing between start of list and last line of text, causing issues in rendering the list.
> fix bulleted list formatting

- episodes/4-advanced-layer-types.md
> Correct image dimensions

- learners/reference.md
> add Dive into Deep Learning to list of resources

- episodes/2-keras.md
Fixes #575
I decided not to change the questions, but instead elaborate the first answer. I disambiguated what was "it" in the original sentence and added a hint on what is yet to come, which is using the test set to measure the model performance.
> Clarify the solution which describes the need for a test set

- .github/workflows/linkspector.yml
- .linkspector.yml
- episodes/2-keras.md
- learners/reference.md
> Add Linkspector
